apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: pingpong
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: "api"
      src: "."
      dockerfileName: "Dockerfile"
      ports:
        - name: http
          port: 8080
      public: true
      authentication:
        clientCertificate:
          verification: "optional_no_ca"
          passCertificateToUpstream: true
